package com.sun.minicpmo_android.ui.theme

import androidx.compose.ui.graphics.Color

// Lighthouse brand palette: calm ocean blue, clear cyan, and a restrained care green.
val LighthouseBlue = Color(0xFF0369A1)
val LighthouseBlueDark = Color(0xFF7DD3FC)
val LighthouseGreen = Color(0xFF157F3B)
val LighthouseTeal = Color(0xFF0F766E)

val LighthouseBackground = Color(0xFFF0F9FF)
val LighthouseSurface = Color(0xFFFFFFFF)
val LighthouseInk = Color(0xFF0C4A6E)
val LighthouseMuted = Color(0xFF415B6B)
val LighthouseOutline = Color(0xFF7593A5)
val LighthouseDanger = Color(0xFFB91C1C)

internal val LighthousePrimaryContainer = Color(0xFFD5EFFF)
internal val LighthouseSecondaryContainer = Color(0xFFCDEFD8)
internal val LighthouseOnSecondaryContainer = Color(0xFF0B3B21)
internal val LighthouseTertiaryContainer = Color(0xFFBCEDEA)
internal val LighthouseOnTertiaryContainer = Color(0xFF073B37)
internal val LighthouseSurfaceVariant = Color(0xFFDCEAF0)
internal val LighthouseOutlineVariant = Color(0xFFB9CBD4)
internal val LighthouseInverseSurface = Color(0xFF17333F)
internal val LighthouseInverseOnSurface = Color(0xFFE5F4F9)
internal val LighthouseErrorContainer = Color(0xFFFFDAD6)
internal val LighthouseOnErrorContainer = Color(0xFF410002)
internal val LighthouseSurfaceDim = Color(0xFFD5E4EA)
internal val LighthouseSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val LighthouseSurfaceContainerLow = Color(0xFFF2F8FB)
internal val LighthouseSurfaceContainer = Color(0xFFEBF3F7)
internal val LighthouseSurfaceContainerHigh = Color(0xFFE3EDF2)
internal val LighthouseSurfaceContainerHighest = Color(0xFFDAE7ED)

val LighthouseDarkBackground = Color(0xFF071A24)
val LighthouseDarkSurface = Color(0xFF0E2A38)
val LighthouseDarkInk = Color(0xFFE0F2FE)

internal val LighthouseDarkPrimaryContainer = Color(0xFF075985)
internal val LighthouseDarkSecondary = Color(0xFF86EFAC)
internal val LighthouseDarkSecondaryContainer = Color(0xFF1C5735)
internal val LighthouseDarkOnSecondaryContainer = Color(0xFFB5F5C8)
internal val LighthouseDarkTertiary = Color(0xFF76D7D0)
internal val LighthouseDarkTertiaryContainer = Color(0xFF00504C)
internal val LighthouseDarkOnTertiaryContainer = Color(0xFF99F2EA)
internal val LighthouseDarkSurfaceVariant = Color(0xFF294955)
internal val LighthouseDarkMuted = Color(0xFFB7D3DF)
internal val LighthouseDarkOutline = Color(0xFF8BA6B2)
internal val LighthouseDarkOutlineVariant = Color(0xFF3A5561)
internal val LighthouseDarkInverseSurface = Color(0xFFD9EAF1)
internal val LighthouseDarkInverseOnSurface = Color(0xFF17333F)
internal val LighthouseDarkError = Color(0xFFFFB4AB)
internal val LighthouseDarkOnError = Color(0xFF690005)
internal val LighthouseDarkErrorContainer = Color(0xFF93000A)
internal val LighthouseDarkOnErrorContainer = Color(0xFFFFDAD6)
internal val LighthouseDarkSurfaceBright = Color(0xFF304C59)
internal val LighthouseDarkSurfaceDim = Color(0xFF071A24)
internal val LighthouseDarkSurfaceContainerLowest = Color(0xFF04131B)
internal val LighthouseDarkSurfaceContainerLow = Color(0xFF0A222D)
internal val LighthouseDarkSurfaceContainer = Color(0xFF0E2A38)
internal val LighthouseDarkSurfaceContainerHigh = Color(0xFF173642)
internal val LighthouseDarkSurfaceContainerHighest = Color(0xFF21414E)
