export const HOUSEHOLD_SECURITY_CONFIG = Symbol('HOUSEHOLD_SECURITY_CONFIG');
export const HOUSEHOLD_CLOCK = Symbol('HOUSEHOLD_CLOCK');
export const INVITATION_DELIVERY_PORT = Symbol('INVITATION_DELIVERY_PORT');

export const HOUSEHOLD_ROLE_SCOPE = 'HOUSEHOLD';
export const HOUSEHOLD_ROLE_CODES = ['OWNER', 'CAREGIVER', 'VIEWER'] as const;
export type HouseholdRoleCode = (typeof HOUSEHOLD_ROLE_CODES)[number];

export const ACTIVE_HOUSEHOLD_STATUS = 'ACTIVE';
export const ACTIVE_MEMBER_STATUS = 'ACTIVE';
export const LEFT_MEMBER_STATUS = 'LEFT';
export const ACTIVE_RECIPIENT_STATUS = 'ACTIVE';
export const ACTIVE_AUTHORITY_STATUS = 'ACTIVE';
export const REVOKED_AUTHORITY_STATUS = 'REVOKED';

export const DEFAULT_INVITATION_TTL_SECONDS = 72 * 60 * 60;
