bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 128
timeout 0
tcp-keepalive 300

dir /data
appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 16mb
save ""

maxclients 64
maxmemory 64mb
maxmemory-policy noeviction

loglevel notice
databases 2
