[Unit]
Before=openbmb-hybrid-recovery.service

[Service]
ExecStart=
ExecStart=/usr/local/sbin/openbmb-stack-control start
ExecReload=
ExecReload=/usr/local/sbin/openbmb-stack-control reload
ExecStop=
ExecStop=/usr/local/sbin/openbmb-stack-control stop
