[Unit]
Requires=openbmb-hybrid-recovery.service openbmb.service
After=openbmb-hybrid-recovery.service openbmb.service

[Service]
ExecStart=
ExecStart=/usr/local/sbin/openbmb-backup-control
ExecStopPost=
ExecStopPost=/usr/local/sbin/openbmb-stack-control reload
ReadWritePaths=/etc/caddy /opt/openbmb /var/lib/openbmb /var/log/caddy
